# Generated by Django 5.2.4 on 2025-08-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_view_user_list", "Can view user list"), ("can_ban", "Can ban user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
