# Generated by Django 5.2.3 on 2025-07-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите тему письма", max_length=100, verbose_name="Тема письма"),
                ),
                (
                    "body",
                    models.TextField(help_text="Напишите текст письма", max_length=500, verbose_name="Тело письма"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(help_text="Введите e-mail", max_length=254, unique=True, verbose_name="Email"),
                ),
                ("full_name", models.CharField(help_text="Введите ФИО", max_length=60, verbose_name="ФИО")),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Добавьте комментарий", max_length=500, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="MailingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_first_sent", models.DateTimeField(auto_now_add=True, verbose_name="Дата первой отправки")),
                ("date_last_sent", models.DateTimeField(auto_now=True, verbose_name="Дата последней отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        help_text="Выберите статус",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Введите сообщение",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        help_text="Введите получателей", to="newsletter.recipient", verbose_name="Получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status"],
            },
        ),
        migrations.CreateModel(
            name="SendAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failure", "Не успешно")], verbose_name="Статус"
                    ),
                ),
                ("response", models.TextField(blank=True, verbose_name="Ответ почтового сервера")),
                (
                    "mailing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.mailinglist",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние рассылки",
                "verbose_name_plural": "Состояния рассылок",
                "ordering": ["status", "date"],
            },
        ),
    ]
