# Generated by Django 5.2.4 on 2025-08-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_sendattempt_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailinglist",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_view_mailing_list", "Can view mailing list"),
                    ("can_turn_off", "Can turn off mailing list"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["title"],
                "permissions": [("can_view_message", "Can view message")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email"],
                "permissions": [("can_view_recipient", "Can view recipient")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="sendattempt",
            options={
                "ordering": ["status", "date"],
                "permissions": [("can_view_attempts", "Can view sent attempts")],
                "verbose_name": "Состояние рассылки",
                "verbose_name_plural": "Состояния рассылок",
            },
        ),
    ]
